### ISSUE TITLE
Boot from EFUSE, Autoload Fail !

### ISSUE THREAD

**Issue by AaronDot** [lwfinger/rtl8188gu#10]
Hi, Do you have any issue about the boot failure with  rtl8188gu？
Do you have the correct driver the series devices?

**Comment by AaronDot** [comment]
The error log:
[ 3174.480438] usb 1-3: USB disconnect, device number 5
[ 3174.787370] usb 1-3: new high-speed USB device number 6 using xhci_hcd
[ 3174.937763] usb 1-3: New USB device found, idVendor=0bda, idProduct=b711, bcdDevice= 2.00
[ 3174.937773] usb 1-3: New USB device strings: Mfr=1, Product=2, SerialNumber=3
[ 3174.937778] usb 1-3: Product: 802.11n WLAN Adapter
[ 3174.937782] usb 1-3: Manufacturer: Realtek
[ 3174.937785] usb 1-3: SerialNumber: 00E04CB82101
[ 3318.672671] RTW: module init start
[ 3318.672678] RTW: rtl8188gtvu v5.7.4.1_35314.20191015
[ 3318.672680] RTW: build time: Oct 14 2020 09:59:35
[ 3318.672714] RTW: rtw_inetaddr_notifier_register
[ 3318.672767] RTW: 
               usb_endpoint_descriptor(0):
[ 3318.672770] RTW: bLength=7
[ 3318.672771] RTW: bDescriptorType=5
[ 3318.672772] RTW: bEndpointAddress=84
[ 3318.672773] RTW: wMaxPacketSize=512
[ 3318.672774] RTW: bInterval=0
[ 3318.672775] RTW: RT_usb_endpoint_is_bulk_in = 4
[ 3318.672776] RTW: 
               usb_endpoint_descriptor(1):
[ 3318.672777] RTW: bLength=7
[ 3318.672778] RTW: bDescriptorType=5
[ 3318.672779] RTW: bEndpointAddress=5
[ 3318.672780] RTW: wMaxPacketSize=512
[ 3318.672781] RTW: bInterval=0
[ 3318.672782] RTW: RT_usb_endpoint_is_bulk_out = 5
[ 3318.672783] RTW: 
               usb_endpoint_descriptor(2):
[ 3318.672784] RTW: bLength=7
[ 3318.672785] RTW: bDescriptorType=5
[ 3318.672786] RTW: bEndpointAddress=6
[ 3318.672787] RTW: wMaxPacketSize=512
[ 3318.672788] RTW: bInterval=0
[ 3318.672788] RTW: RT_usb_endpoint_is_bulk_out = 6
[ 3318.672789] RTW: 
               usb_endpoint_descriptor(3):
[ 3318.672790] RTW: bLength=7
[ 3318.672791] RTW: bDescriptorType=5
[ 3318.672792] RTW: bEndpointAddress=87
[ 3318.672793] RTW: wMaxPacketSize=64
[ 3318.672794] RTW: bInterval=3
[ 3318.672795] RTW: RT_usb_endpoint_is_int_in = 7, Interval = 3
[ 3318.672797] RTW: 
               usb_endpoint_descriptor(4):
[ 3318.672798] RTW: bLength=7
[ 3318.672799] RTW: bDescriptorType=5
[ 3318.672800] RTW: bEndpointAddress=8
[ 3318.672801] RTW: wMaxPacketSize=512
[ 3318.672802] RTW: bInterval=0
[ 3318.672803] RTW: RT_usb_endpoint_is_bulk_out = 8
[ 3318.672804] RTW: 
               usb_endpoint_descriptor(5):
[ 3318.672805] RTW: bLength=7
[ 3318.672806] RTW: bDescriptorType=5
[ 3318.672807] RTW: bEndpointAddress=9
[ 3318.672808] RTW: wMaxPacketSize=512
[ 3318.672809] RTW: bInterval=0
[ 3318.672810] RTW: RT_usb_endpoint_is_bulk_out = 9
[ 3318.672811] RTW: nr_endpoint=6, in_num=2, out_num=4

[ 3318.672812] RTW: USB_SPEED_HIGH
[ 3318.672815] RTW: CHIP TYPE: RTL8188GTVU
[ 3319.196930] RTW: reg 0xf0, usb read 4 fail, status:-110 value=0x0, vendorreq_times:1
[ 3319.713109] RTW: reg 0xf0, usb read 4 fail, status:-110 value=0x0, vendorreq_times:2
[ 3320.220855] RTW: reg 0xf0, usb read 4 fail, status:-110 value=0x0, vendorreq_times:3
[ 3320.732063] RTW: reg 0xf0, usb read 4 fail, status:-110 value=0x0, vendorreq_times:4
[ 3321.243808] RTW: reg 0xf0, usb read 4 fail, status:-110 value=0x0, vendorreq_times:5
[ 3321.243818] RTW: [dvobj:00000000a7f1419c][ERROR] continual_io_error:5 > 4
[ 3321.243823] RTW: rtw_hal_config_rftype RF_Type is 0 TotalTxPath is 1
[ 3321.243828] RTW: Chip Version Info: CHIP_8188GTV_Normal_Chip_TSMC_A_CUT_1T1R_RomVer(0)
[ 3321.243833] RTW: _ConfigChipOutEP_8188GTV OutEpQueueSel(0x07), OutEpNumber(4)
[ 3321.243837] RTW: EEPROM type is E-FUSE
[ 3321.243841] RTW: Boot from EFUSE, Autoload Fail !
[ 3321.243857] RTW: HW EFUSE
[ 3321.243861] RTW: 0x000: FF FF FF FF  FF FF FF FF  FF FF FF FF  FF FF FF FF  
[ 3321.243872] RTW: 0x010: FF FF FF FF  FF FF FF FF  FF FF FF FF  FF FF FF FF  
[ 3321.243882] RTW: 0x020: FF FF FF FF  FF FF FF FF  FF FF FF FF  FF FF FF FF  
[ 3321.243893] RTW: 0x030: FF FF FF FF  FF FF FF FF  FF FF FF FF  FF FF FF FF  
[ 3321.243903] RTW: 0x040: FF FF FF FF  FF FF FF FF  FF FF FF FF  FF FF FF FF  
[ 3321.243912] RTW: 0x050: FF FF FF FF  FF FF FF FF  FF FF FF FF  FF FF FF FF  
[ 3321.243922] RTW: 0x060: FF FF FF FF  FF FF FF FF  FF FF FF FF  FF FF FF FF  
[ 3321.243931] RTW: 0x070: FF FF FF FF  FF FF FF FF  FF FF FF FF  FF FF FF FF  
[ 3321.243941] RTW: 0x080: FF FF FF FF  FF FF FF FF  FF FF FF FF  FF FF FF FF  
[ 3321.243951] RTW: 0x090: FF FF FF FF  FF FF FF FF  FF FF FF FF  FF FF FF FF  
[ 3321.243962] RTW: 0x0A0: FF FF FF FF  FF FF FF FF  FF FF FF FF  FF FF FF FF  
[ 3321.243971] RTW: 0x0B0: FF FF FF FF  FF FF FF FF  FF FF FF FF  FF FF FF FF  
[ 3321.243981] RTW: 0x0C0: FF FF FF FF  FF FF FF FF  FF FF FF FF  FF FF FF FF  
[ 3321.243991] RTW: 0x0D0: FF FF FF FF  FF FF FF FF  FF FF FF FF  FF FF FF FF  
[ 3321.244000] RTW: 0x0E0: FF FF FF FF  FF FF FF FF  FF FF FF FF  FF FF FF FF  
[ 3321.244010] RTW: 0x0F0: FF FF FF FF  FF FF FF FF  FF FF FF FF  FF FF FF FF  
[ 3321.244019] RTW: 0x100: FF FF FF FF  FF FF FF FF  FF FF FF FF  FF FF FF FF  
[ 3321.244028] RTW: 0x110: FF FF FF FF  FF FF FF FF  FF FF FF FF  FF FF FF FF  
[ 3321.244037] RTW: 0x120: FF FF FF FF  FF FF FF FF  FF FF FF FF  FF FF FF FF  
[ 3321.244048] RTW: 0x130: FF FF FF FF  FF FF FF FF  FF FF FF FF  FF FF FF FF  
[ 3321.244058] RTW: 0x140: FF FF FF FF  FF FF FF FF  FF FF FF FF  FF FF FF FF  
[ 3321.244067] RTW: 0x150: FF FF FF FF  FF FF FF FF  FF FF FF FF  FF FF FF FF  
[ 3321.244077] RTW: 0x160: FF FF FF FF  FF FF FF FF  FF FF FF FF  FF FF FF FF  
[ 3321.244087] RTW: 0x170: FF FF FF FF  FF FF FF FF  FF FF FF FF  FF FF FF FF  
[ 3321.244098] RTW: 0x180: FF FF FF FF  FF FF FF FF  FF FF FF FF  FF FF FF FF  
[ 3321.244106] RTW: 0x190: FF FF FF FF  FF FF FF FF  FF FF FF FF  FF FF FF FF  
[ 3321.244115] RTW: 0x1A0: FF FF FF FF  FF FF FF FF  FF FF FF FF  FF FF FF FF  
[ 3321.244124] RTW: 0x1B0: FF FF FF FF  FF FF FF FF  FF FF FF FF  FF FF FF FF  
[ 3321.244135] RTW: 0x1C0: FF FF FF FF  FF FF FF FF  FF FF FF FF  FF FF FF FF  
[ 3321.244145] RTW: 0x1D0: FF FF FF FF  FF FF FF FF  FF FF FF FF  FF FF FF FF  
[ 3321.244155] RTW: 0x1E0: FF FF FF FF  FF FF FF FF  FF FF FF FF  FF FF FF FF  
[ 3321.244164] RTW: 0x1F0: FF FF FF FF  FF FF FF FF  FF FF FF FF  FF FF FF FF  
[ 3321.244211] RTW: rtw_read_efuse_from_file /system/etc/wifi/wifi_efuse_8188gtvu.map is not readable
[ 3321.244214] RTW: ERROR invalid phy efuse and read from file fail, will use driver default!!
[ 3321.244217] RTW: EEPROM ID(0xffff) is invalid!!
[ 3321.244219] RTW: EEPROM VID = 0x   0
[ 3321.244221] RTW: EEPROM PID = 0x   0
[ 3321.244240] RTW: rtw_read_macaddr_from_file /data/wifimac.txt is not readable
[ 3321.244247] RTW: [A] 2G G00 CCK-1T base:34 from IC_DEF
[ 3321.244250] RTW: [A] 2G G01 CCK-1T base:34 from IC_DEF
[ 3321.244252] RTW: [A] 2G G02 CCK-1T base:34 from IC_DEF
[ 3321.244254] RTW: [A] 2G G03 CCK-1T base:34 from IC_DEF
[ 3321.244257] RTW: [A] 2G G04 CCK-1T base:34 from IC_DEF
[ 3321.244259] RTW: [A] 2G G05 CCK-1T base:34 from IC_DEF
[ 3321.244262] RTW: [A] 2G G00 BW40-1S base:39 from IC_DEF
[ 3321.244265] RTW: [A] 2G G01 BW40-1S base:39 from IC_DEF
[ 3321.244266] RTW: [A] 2G G02 BW40-1S base:39 from IC_DEF
[ 3321.244270] RTW: [A] 2G G03 BW40-1S base:39 from IC_DEF
[ 3321.244273] RTW: [A] 2G G04 BW40-1S base:39 from IC_DEF
[ 3321.244277] RTW: hal_com_config_channel_plan use def_chplan:0x20
[ 3322.236570] RTW: efuse_OneByteRead: [ERROR] addr=0xee bResult=0 time out 1s !!!
[ 3322.236576] RTW: efuse_OneByteRead: [ERROR] EFUSE_CTRL =0x00000000 !!!
[ 3323.228834] RTW: efuse_OneByteRead: [ERROR] addr=0xef bResult=0 time out 1s !!!
[ 3323.228840] RTW: efuse_OneByteRead: [ERROR] EFUSE_CTRL =0x00000000 !!!
[ 3323.228843] RTW: kfree Pwr Trim flag:0
[ 3323.283631] RTW: ERROR HalPwrSeqCmdParsing: Fail to polling Offset[0x6]=00
[ 3323.283683] RTW: rtl8188gtv_FirmwareDownload((null)) tmp_ps=0
[ 3323.283689] RTW: rtl8188gtv_FirmwareDownload fw: FW_NIC, size: 21768
[ 3323.283693] RTW: rtl8188gtv_FirmwareDownload: fw_ver=6 fw_subver=0000 sig=0x88f1, Month=07, Date=30, Hour=11, Minute=06
[ 3323.283695] RTW: rtl8188gtv_FirmwareDownload(): Shift for fw header!
[ 3323.283697] RTW: rtl8188gtv_FirmwareDownload by IO write!
[ 3323.484732] RTW: _FWDownloadEnable: !!!!!!!!Write 0x80 Fail!: count = 101
[ 3323.484738] RTW: _8051Reset8188: Finish
[ 3323.484741] RTW: _FWFreeToGo: Polling FW ready Fail! (1, 0ms), REG_MCUFWDL:0x00000000
[ 3323.484742] RTW: rtl8188gtv_FirmwareDownload fail. write_fw:0, 200ms
[ 3323.484745] RTW:  <=== rtl8188gtv_FirmwareDownload()
[ 3323.484748] RTW: CardDisableRTL8188GTVU
[ 3323.484756] RTW: hal_read_mac_hidden_rpt Fail! (0, 256ms), fwdl:0, id:0xfd
[ 3323.484758] RTW: rtw_hal_read_chip_info in 2240 ms
[ 3323.484775] RTW: rtw_usb_primary_adapter_init Failed!
[ 3323.484777] RTW: usb attached..., try to reset usb device
[ 3323.616269] usb 1-3: reset high-speed USB device number 6 using xhci_hcd
[ 3323.775754] usbcore: registered new interface driver rtl8188gtvu
[ 3323.775769] RTW: module init ret=0
[ 3374.917289] usb 1-3: USB disconnect, device number 6

**Comment by lwfinger** [comment]
Therre is NO Linux driver for this chip. This repo was an attempt to set one up, but ALL available drivers fail!
