### ISSUE TITLE
Compile success but dkms not showing the rtl8188gu.

### ISSUE THREAD

**Issue by brucelelele** [lwfinger/rtl8188gu#16]
Device: Tenda U2
Chipset: Realtek 8188GU Wireless LAN802.11n USB NIC

**Comment by lwfinger** [comment]
I do not support dkms. If you want dkms support for the rtl8188gu, you will need to prepare the necessary control files.

Just use 'make' and 'sudo make install' whenever your kernel changes!

**Comment by agentdiary** [comment]
Thank you, lwfinger! I just sucessfully make and make install but nothing really happen after that. I use iwconfig and detect nothing change. And I can see the wireless adapter already exist but still no driver installed. Do you know what is the wrong here?&nbsp;



---Original---
From: ***@***.***&gt;
Date: Mon, Oct 16, 2023 23:41 PM
To: ***@***.***&gt;;
Cc: ***@***.******@***.***&gt;;
Subject: Re: [lwfinger/rtl8188gu] Compile success but dkms not showing thertl8188gu. (Issue #16)




 
I do not support dkms. If you want dkms support for the rtl8188gu, you will need to prepare the necessary control files.
 
Just use 'make' and 'sudo make install' whenever your kernel changes!

**Comment by lwfinger** [comment]
Have you rebooted, or at least loaded the driver? Perhaps you do not really have an rtl8188gu. Run the following commands and post the output:
lsusb
lsmod | grep 8188

**Comment by agentdiary** [comment]
---Original---
From: ***@***.***&gt;
Date: Tue, Oct 17, 2023 03:27 AM
To: ***@***.***&gt;;
Cc: ***@***.******@***.***&gt;;
Subject: Re: [lwfinger/rtl8188gu] Compile success but dkms not showing thertl8188gu. (Issue #16)




 
Have you rebooted, or at least loaded the driver? Perhaps you do not really have an rtl8188gu. Run the following commands and post the output:
 lspci
 lsmod | grep 8188

**Comment by agentdiary** [comment]
I am sorry I think I chose the wrong&nbsp;
Screenshot in the last sent.Here should be ok.

---Original---
From: ***@***.***&gt;
Date: Tue, Oct 17, 2023 03:27 AM
To: ***@***.***&gt;;
Cc: ***@***.******@***.***&gt;;
Subject: Re: [lwfinger/rtl8188gu] Compile success but dkms not showing thertl8188gu. (Issue #16)




 
Have you rebooted, or at least loaded the driver? Perhaps you do not really have an rtl8188gu. Run the following commands and post the output:
 lspci
 lsmod | grep 8188

**Comment by dubhater** [comment]
This version of the driver has been broken for years. Even if you compile it, it won't work: https://github.com/lwfinger/rtl8188gu/issues/8

**Comment by sevven213** [comment]
HELP ME TO INSTALL DRIVER FOR TENDA U2 adapter plz...

**Comment by sevven213** [comment]
@brucelelele i have the same adapter and the same problem i cant install the driver in kali linux
