### ISSUE TITLE
help please. got some error message

### ISSUE THREAD

**Issue by aimlessness99** [lwfinger/rtl8188gu#5]
ubuntu 20.04
after make && sudo make install

i plugin the usb wifi device:
work/soft/drivers/rtl8188gu$ lsusb | grep 0bda
Bus 002 Device 016: ID 0bda:b711 Realtek Semiconductor Corp. 802.11n WLAN Adapter

but ifconfig shows no new network interface and got some error message like this 
:/lib/firmware/rtlwifi$ sudo dmesg -c
[ 5483.389947] usb 2-6: new high-speed USB device number 15 using xhci_hcd
[ 5483.410498] usb 2-6: New USB device found, idVendor=0bda, idProduct=1a2b, bcdDevice= 2.00
[ 5483.410504] usb 2-6: New USB device strings: Mfr=1, Product=2, SerialNumber=0
[ 5483.410508] usb 2-6: Product: DISK
[ 5483.410511] usb 2-6: Manufacturer: Realtek
[ 5483.412360] usb-storage 2-6:1.0: USB Mass Storage device detected
[ 5483.413047] scsi host6: usb-storage 2-6:1.0
[ 5484.430671] scsi 6:0:0:0: CD-ROM            Realtek  USB Disk autorun 1.00 PQ: 0 ANSI: 0 CCS
[ 5484.431409] sr 6:0:0:0: [sr0] scsi-1 drive
[ 5484.458375] sr 6:0:0:0: Attached scsi CD-ROM sr0
[ 5484.458625] sr 6:0:0:0: Attached scsi generic sg2 type 5
[ 5484.469120] sr 6:0:0:0: [sr0] tag#0 FAILED Result: hostbyte=DID_ERROR driverbyte=DRIVER_OK
[ 5484.469124] sr 6:0:0:0: [sr0] tag#0 CDB: Read(10) 28 00 00 00 ff fc 00 00 02 00
[ 5484.469128] blk_update_request: I/O error, dev sr0, sector 262128 op 0x0:(READ) flags 0x80700 phys_seg 1 prio class 0
[ 5484.477843] scsi 6:0:0:0: rejecting I/O to dead device
[ 5484.477848] blk_update_request: I/O error, dev sr0, sector 262128 op 0x0:(READ) flags 0x0 phys_seg 1 prio class 0
[ 5484.477851] buffer_io_error: 94 callbacks suppressed
[ 5484.477852] Buffer I/O error on dev sr0, logical block 32766, async page read
[ 5484.477904] Buffer I/O error on dev sr0, logical block 0, async page read
[ 5484.477911] Buffer I/O error on dev sr0, logical block 0, async page read
[ 5484.477916] Buffer I/O error on dev sr0, logical block 0, async page read
[ 5484.477921] Buffer I/O error on dev sr0, logical block 0, async page read
[ 5484.477926] Buffer I/O error on dev sr0, logical block 0, async page read
[ 5484.477930] Buffer I/O error on dev sr0, logical block 0, async page read
[ 5484.477935] Buffer I/O error on dev sr0, logical block 0, async page read
[ 5484.477939] Buffer I/O error on dev sr0, logical block 0, async page read
[ 5484.477943] Buffer I/O error on dev sr0, logical block 0, async page read
[ 5484.494896] usb 2-6: USB disconnect, device number 15
[ 5484.873952] usb 2-6: new high-speed USB device number 16 using xhci_hcd
[ 5484.894457] usb 2-6: New USB device found, idVendor=0bda, idProduct=b711, bcdDevice= 2.00
[ 5484.894463] usb 2-6: New USB device strings: Mfr=1, Product=2, SerialNumber=3
[ 5484.894467] usb 2-6: Product: 802.11n WLAN Adapter
[ 5484.894470] usb 2-6: Manufacturer: Realtek
[ 5484.894472] usb 2-6: SerialNumber: 00E04CB82101
[ 5484.898319] RTW: 
               usb_endpoint_descriptor(0):
[ 5484.898324] RTW: bLength=7
[ 5484.898326] RTW: bDescriptorType=5
[ 5484.898328] RTW: bEndpointAddress=84
[ 5484.898330] RTW: wMaxPacketSize=512
[ 5484.898332] RTW: bInterval=0
[ 5484.898334] RTW: RT_usb_endpoint_is_bulk_in = 4
[ 5484.898336] RTW: 
               usb_endpoint_descriptor(1):
[ 5484.898337] RTW: bLength=7
[ 5484.898339] RTW: bDescriptorType=5
[ 5484.898341] RTW: bEndpointAddress=5
[ 5484.898343] RTW: wMaxPacketSize=512
[ 5484.898345] RTW: bInterval=0
[ 5484.898347] RTW: RT_usb_endpoint_is_bulk_out = 5
[ 5484.898349] RTW: 
               usb_endpoint_descriptor(2):
[ 5484.898351] RTW: bLength=7
[ 5484.898352] RTW: bDescriptorType=5
[ 5484.898354] RTW: bEndpointAddress=6
[ 5484.898356] RTW: wMaxPacketSize=512
[ 5484.898358] RTW: bInterval=0
[ 5484.898360] RTW: RT_usb_endpoint_is_bulk_out = 6
[ 5484.898361] RTW: 
               usb_endpoint_descriptor(3):
[ 5484.898363] RTW: bLength=7
[ 5484.898365] RTW: bDescriptorType=5
[ 5484.898367] RTW: bEndpointAddress=87
[ 5484.898369] RTW: wMaxPacketSize=64
[ 5484.898371] RTW: bInterval=3
[ 5484.898374] RTW: RT_usb_endpoint_is_int_in = 7, Interval = 3
[ 5484.898376] RTW: 
               usb_endpoint_descriptor(4):
[ 5484.898378] RTW: bLength=7
[ 5484.898380] RTW: bDescriptorType=5
[ 5484.898381] RTW: bEndpointAddress=8
[ 5484.898383] RTW: wMaxPacketSize=512
[ 5484.898385] RTW: bInterval=0
[ 5484.898387] RTW: RT_usb_endpoint_is_bulk_out = 8
[ 5484.898389] RTW: 
               usb_endpoint_descriptor(5):
[ 5484.898391] RTW: bLength=7
[ 5484.898393] RTW: bDescriptorType=5
[ 5484.898395] RTW: bEndpointAddress=9
[ 5484.898397] RTW: wMaxPacketSize=512
[ 5484.898399] RTW: bInterval=0
[ 5484.898401] RTW: RT_usb_endpoint_is_bulk_out = 9
[ 5484.898404] RTW: nr_endpoint=6, in_num=2, out_num=4

[ 5484.898405] RTW: USB_SPEED_HIGH
[ 5484.898445] RTW: Peter : Step2
[ 5484.898491] RTW: ### rtw_hal_ops_check - Error : Please hook hal_func.read_chip_version ###
[ 5484.898494] RTW: ### rtw_hal_ops_check - Error : Please hook hal_func.init_default_value ###
[ 5484.898496] RTW: ### rtw_hal_ops_check - Error : Please hook hal_func.intf_chip_configure ###
[ 5484.898499] RTW: ### rtw_hal_ops_check - Error : Please hook hal_func.read_adapter_info ###
[ 5484.898502] RTW: ### rtw_hal_ops_check - Error : Please hook hal_func.hal_power_on ###
[ 5484.898505] RTW: ### rtw_hal_ops_check - Error : Please hook hal_func.hal_power_off ###
[ 5484.898508] RTW: ### rtw_hal_ops_check - Error : Please hook hal_func.hal_init ###
[ 5484.898510] RTW: ### rtw_hal_ops_check - Error : Please hook hal_func.hal_deinit ###
[ 5484.898513] RTW: ### rtw_hal_ops_check - Error : Please hook hal_func.init_xmit_priv ###
[ 5484.898516] RTW: ### rtw_hal_ops_check - Error : Please hook hal_func.free_xmit_priv ###
[ 5484.898518] RTW: ### rtw_hal_ops_check - Error : Please hook hal_func.hal_xmit ###
[ 5484.898522] RTW: ### rtw_hal_ops_check - Error : Please hook hal_func.mgnt_xmit ###
[ 5484.898524] RTW: ### rtw_hal_ops_check - Error : Please hook hal_func.hal_xmitframe_enqueue ###
[ 5484.898527] RTW: ### rtw_hal_ops_check - Error : Please hook hal_func.init_recv_priv ###
[ 5484.898530] RTW: ### rtw_hal_ops_check - Error : Please hook hal_func.free_recv_priv ###
[ 5484.898532] RTW: ### rtw_hal_ops_check - Error : Please hook hal_func.inirp_init ###
[ 5484.898535] RTW: ### rtw_hal_ops_check - Error : Please hook hal_func.inirp_deinit ###
[ 5484.898538] RTW: ### rtw_hal_ops_check - Error : Please hook hal_func.dm_init ###
[ 5484.898541] RTW: ### rtw_hal_ops_check - Error : Please hook hal_func.dm_deinit ###
[ 5484.898543] RTW: ### rtw_hal_ops_check - Error : Please hook hal_func.hal_dm_watchdog ###
[ 5484.898546] RTW: ### rtw_hal_ops_check - Error : Please hook hal_func.set_chnl_bw_handler ###
[ 5484.898548] RTW: ### rtw_hal_ops_check - Error : Please hook hal_func.set_hw_reg_handler ###
[ 5484.898551] RTW: ### rtw_hal_ops_check - Error : Please hook hal_func.GetHwRegHandler ###
[ 5484.898554] RTW: ### rtw_hal_ops_check - Error : Please hook hal_func.get_hal_def_var_handler ###
[ 5484.898556] RTW: ### rtw_hal_ops_check - Error : Please hook hal_func.SetHalDefVarHandler ###
[ 5484.898559] RTW: ### rtw_hal_ops_check - Error : Please hook hal_func.GetHalODMVarHandler ###
[ 5484.898561] RTW: ### rtw_hal_ops_check - Error : Please hook hal_func.SetHalODMVarHandler ###
[ 5484.898564] RTW: ### rtw_hal_ops_check - Error : Please hook hal_func.SetBeaconRelatedRegistersHandler ###
[ 5484.898566] RTW: ### rtw_hal_ops_check - Error : Please hook hal_func.fill_h2c_cmd ###
[ 5484.898568] RTW: ### rtw_hal_ops_check - Error : Please hook hal_func.c2h_handler ###
[ 5484.898570] RTW: ### rtw_hal_ops_check - Error : Please hook hal_func.fill_fake_txdesc ###
[ 5484.898572] RTW: ### rtw_hal_ops_check - Error : Please hook hal_func.hal_get_tx_buff_rsvd_page_num ###
[ 5484.898573] RTW: ### rtw_hal_ops_check - Error : Please hook hal_func.fw_dl ###
[ 5484.898575] RTW: ### rtw_hal_ops_check - Error : Please hook hal_func.get_tx_power_index_handler ###
[ 5484.898588] RTW: rtw_usb_primary_adapter_init Failed!
[ 5484.898589] RTW: usb attached..., try to reset usb device
[ 5485.026275] usb 2-6: reset high-speed USB device number 16 using xhci_hcd
[ 5485.047102] option 2-6:1.0: GSM modem (1-port) converter detected
[ 5485.047461] usb 2-6: GSM modem (1-port) converter now attached to ttyUSB0

**Comment by lwfinger** [comment]
T have not found a Linux driver for the RTL8188GU. Those that have been posted are for different devices, which is why you get errors. At this point, we do not have a solution.
