### ISSUE TITLE
Doesn't work with MW150US on Ubuntu 18.04

### ISSUE THREAD

**Issue by zifeis** [lwfinger/rtl8188gu#6]
Device doesn't show up.

Dmesg info after modprobe 8188gu
[Dmesg.txt](https://github.com/lwfinger/rtl8188gu/files/4757558/Dmesg.txt)

Vendor: Mercury MW150US 
Os: Ubuntu 18.04
Kernel: 5.3.0-56

**Comment by lwfinger** [comment]
Obviously you missed all the places where I wrote that there are no Linux drivers for 8188gu devices.

**Comment by wandercn** [comment]
我也遇到8188gu型号驱动问题，自己找资料整理了安装指南.我在Raspberry pi 和 ubuntu 20.0.4都安装成功了。deepin也应该可以。解决了您的问题帮忙点个星星

https://github.com/wandercn/RTL8188GU
