### ISSUE TITLE
Some error in dmesg

### ISSUE THREAD

**Issue by yanlei2017** [lwfinger/rtl8188gu#7]
adapter : tplink-wn725N
OS: ubuntu 18.04 
linux-Kernel: 5.3.0-28-generic
my operation :
1. git clone https://github.com/lwfinger/rtl8188gu.git
2. make all 
3. sudo make install 

COMPILE OUTPUT:--------------------------------

~/wifidriver/rtl8188gu(master) » make all                                                     yl@SupreMe
make ARCH=x86_64 CROSS_COMPILE= -C /lib/modules/5.3.0-28-generic/build M=/home/yl/wifidriver/rtl8188gu  modules
make[1]: Entering directory '/usr/src/linux-headers-5.3.0-28-generic'
  CC [M]  /home/yl/wifidriver/rtl8188gu/core/rtw_cmd.o
  CC [M]  /home/yl/wifidriver/rtl8188gu/core/rtw_security.o
  CC [M]  /home/yl/wifidriver/rtl8188gu/core/rtw_debug.o
  CC [M]  /home/yl/wifidriver/rtl8188gu/core/rtw_io.o
  CC [M]  /home/yl/wifidriver/rtl8188gu/core/rtw_ioctl_query.o
  CC [M]  /home/yl/wifidriver/rtl8188gu/core/rtw_ioctl_set.o
  CC [M]  /home/yl/wifidriver/rtl8188gu/core/rtw_ieee80211.o
  CC [M]  /home/yl/wifidriver/rtl8188gu/core/rtw_mlme.o
  CC [M]  /home/yl/wifidriver/rtl8188gu/core/rtw_mlme_ext.o
  CC [M]  /home/yl/wifidriver/rtl8188gu/core/rtw_mi.o
  CC [M]  /home/yl/wifidriver/rtl8188gu/core/rtw_wlan_util.o
  CC [M]  /home/yl/wifidriver/rtl8188gu/core/rtw_vht.o
  CC [M]  /home/yl/wifidriver/rtl8188gu/core/rtw_pwrctrl.o
  CC [M]  /home/yl/wifidriver/rtl8188gu/core/rtw_rf.o
  CC [M]  /home/yl/wifidriver/rtl8188gu/core/rtw_recv.o
  CC [M]  /home/yl/wifidriver/rtl8188gu/core/rtw_sta_mgt.o
  CC [M]  /home/yl/wifidriver/rtl8188gu/core/rtw_ap.o
  CC [M]  /home/yl/wifidriver/rtl8188gu/core/rtw_xmit.o
  CC [M]  /home/yl/wifidriver/rtl8188gu/core/rtw_p2p.o
  CC [M]  /home/yl/wifidriver/rtl8188gu/core/rtw_rson.o
  CC [M]  /home/yl/wifidriver/rtl8188gu/core/rtw_tdls.o
  CC [M]  /home/yl/wifidriver/rtl8188gu/core/rtw_br_ext.o
  CC [M]  /home/yl/wifidriver/rtl8188gu/core/rtw_iol.o
  CC [M]  /home/yl/wifidriver/rtl8188gu/core/rtw_sreset.o
  CC [M]  /home/yl/wifidriver/rtl8188gu/core/rtw_btcoex_wifionly.o
  CC [M]  /home/yl/wifidriver/rtl8188gu/core/rtw_btcoex.o
  CC [M]  /home/yl/wifidriver/rtl8188gu/core/rtw_beamforming.o
  CC [M]  /home/yl/wifidriver/rtl8188gu/core/rtw_odm.o
  CC [M]  /home/yl/wifidriver/rtl8188gu/core/rtw_rm.o
  CC [M]  /home/yl/wifidriver/rtl8188gu/core/rtw_rm_fsm.o
  CC [M]  /home/yl/wifidriver/rtl8188gu/core/efuse/rtw_efuse.o
  CC [M]  /home/yl/wifidriver/rtl8188gu/os_dep/osdep_service.o
  CC [M]  /home/yl/wifidriver/rtl8188gu/os_dep/linux/os_intfs.o
  CC [M]  /home/yl/wifidriver/rtl8188gu/os_dep/linux/usb_intf.o
  CC [M]  /home/yl/wifidriver/rtl8188gu/os_dep/linux/usb_ops_linux.o
  CC [M]  /home/yl/wifidriver/rtl8188gu/os_dep/linux/ioctl_linux.o
  CC [M]  /home/yl/wifidriver/rtl8188gu/os_dep/linux/xmit_linux.o
  CC [M]  /home/yl/wifidriver/rtl8188gu/os_dep/linux/mlme_linux.o
  CC [M]  /home/yl/wifidriver/rtl8188gu/os_dep/linux/recv_linux.o
  CC [M]  /home/yl/wifidriver/rtl8188gu/os_dep/linux/ioctl_cfg80211.o
  CC [M]  /home/yl/wifidriver/rtl8188gu/os_dep/linux/rtw_cfgvendor.o
  CC [M]  /home/yl/wifidriver/rtl8188gu/os_dep/linux/wifi_regd.o
  CC [M]  /home/yl/wifidriver/rtl8188gu/os_dep/linux/rtw_android.o
  CC [M]  /home/yl/wifidriver/rtl8188gu/os_dep/linux/rtw_proc.o
  CC [M]  /home/yl/wifidriver/rtl8188gu/os_dep/linux/ioctl_mp.o
/home/yl/wifidriver/rtl8188gu/os_dep/linux/ioctl_mp.c: In function ‘rtw_mp_write_reg’:
/home/yl/wifidriver/rtl8188gu/os_dep/linux/ioctl_mp.c:46:2: warning: ISO C90 forbids variable length array ‘input’ [-Wvla]
  char input[wrqu->length + 1];
  ^
/home/yl/wifidriver/rtl8188gu/os_dep/linux/ioctl_mp.c: In function ‘rtw_mp_read_reg’:
/home/yl/wifidriver/rtl8188gu/os_dep/linux/ioctl_mp.c:132:2: warning: ISO C90 forbids variable length array ‘input’ [-Wvla]
  char input[wrqu->length + 1];
  ^
/home/yl/wifidriver/rtl8188gu/os_dep/linux/ioctl_mp.c: In function ‘rtw_mp_write_rf’:
/home/yl/wifidriver/rtl8188gu/os_dep/linux/ioctl_mp.c:266:2: warning: ISO C90 forbids variable length array ‘input’ [-Wvla]
  char input[wrqu->length];
  ^
/home/yl/wifidriver/rtl8188gu/os_dep/linux/ioctl_mp.c: In function ‘rtw_mp_read_rf’:
/home/yl/wifidriver/rtl8188gu/os_dep/linux/ioctl_mp.c:308:2: warning: ISO C90 forbids variable length array ‘input’ [-Wvla]
  char input[wrqu->length];
  ^
/home/yl/wifidriver/rtl8188gu/os_dep/linux/ioctl_mp.c: In function ‘rtw_mp_rate’:
/home/yl/wifidriver/rtl8188gu/os_dep/linux/ioctl_mp.c:417:2: warning: ISO C90 forbids variable length array ‘input’ [-Wvla]
  u8  input[wrqu->length + 1];
  ^
/home/yl/wifidriver/rtl8188gu/os_dep/linux/ioctl_mp.c: In function ‘rtw_mp_channel’:
/home/yl/wifidriver/rtl8188gu/os_dep/linux/ioctl_mp.c:467:2: warning: ISO C90 forbids variable length array ‘input’ [-Wvla]
  u8  input[wrqu->length + 1];
  ^
/home/yl/wifidriver/rtl8188gu/os_dep/linux/ioctl_mp.c: In function ‘rtw_mp_bandwidth’:
/home/yl/wifidriver/rtl8188gu/os_dep/linux/ioctl_mp.c:497:2: warning: ISO C90 forbids variable length array ‘input’ [-Wvla]
  u8  input[wrqu->length];
  ^
/home/yl/wifidriver/rtl8188gu/os_dep/linux/ioctl_mp.c: In function ‘rtw_mp_txpower_index’:
/home/yl/wifidriver/rtl8188gu/os_dep/linux/ioctl_mp.c:530:2: warning: ISO C90 forbids variable length array ‘input’ [-Wvla]
  char input[wrqu->length + 1];
  ^
/home/yl/wifidriver/rtl8188gu/os_dep/linux/ioctl_mp.c: In function ‘rtw_mp_txpower’:
/home/yl/wifidriver/rtl8188gu/os_dep/linux/ioctl_mp.c:559:2: warning: ISO C90 forbids variable length array ‘input’ [-Wvla]
  u8  input[wrqu->length];
  ^
/home/yl/wifidriver/rtl8188gu/os_dep/linux/ioctl_mp.c: In function ‘rtw_mp_ant_tx’:
/home/yl/wifidriver/rtl8188gu/os_dep/linux/ioctl_mp.c:597:2: warning: ISO C90 forbids variable length array ‘input’ [-Wvla]
  u8  input[wrqu->length + 1];
  ^
/home/yl/wifidriver/rtl8188gu/os_dep/linux/ioctl_mp.c: In function ‘rtw_mp_ant_rx’:
/home/yl/wifidriver/rtl8188gu/os_dep/linux/ioctl_mp.c:645:2: warning: ISO C90 forbids variable length array ‘input’ [-Wvla]
  u8  input[wrqu->length + 1];
  ^
/home/yl/wifidriver/rtl8188gu/os_dep/linux/ioctl_mp.c: In function ‘rtw_mp_disable_bt_coexist’:
/home/yl/wifidriver/rtl8188gu/os_dep/linux/ioctl_mp.c:825:2: warning: ISO C90 forbids variable length array ‘input’ [-Wvla]
  u8 input[wrqu->data.length + 1];
  ^
/home/yl/wifidriver/rtl8188gu/os_dep/linux/ioctl_mp.c: In function ‘rtw_mp_arx’:
/home/yl/wifidriver/rtl8188gu/os_dep/linux/ioctl_mp.c:863:2: warning: ISO C90 forbids variable length array ‘input’ [-Wvla]
  u8  input[wrqu->length];
  ^
/home/yl/wifidriver/rtl8188gu/os_dep/linux/ioctl_mp.c: In function ‘rtw_mp_pwrtrk’:
/home/yl/wifidriver/rtl8188gu/os_dep/linux/ioctl_mp.c:1042:2: warning: ISO C90 forbids variable length array ‘input’ [-Wvla]
  u8  input[wrqu->length];
  ^
/home/yl/wifidriver/rtl8188gu/os_dep/linux/ioctl_mp.c: In function ‘rtw_mp_psd’:
/home/yl/wifidriver/rtl8188gu/os_dep/linux/ioctl_mp.c:1080:2: warning: ISO C90 forbids variable length array ‘input’ [-Wvla]
  u8  input[wrqu->length + 1];
  ^
/home/yl/wifidriver/rtl8188gu/os_dep/linux/ioctl_mp.c: In function ‘rtw_mp_dump’:
/home/yl/wifidriver/rtl8188gu/os_dep/linux/ioctl_mp.c:1198:2: warning: ISO C90 forbids variable length array ‘input’ [-Wvla]
  u8  input[wrqu->length];
  ^
/home/yl/wifidriver/rtl8188gu/os_dep/linux/ioctl_mp.c: In function ‘rtw_mp_phypara’:
/home/yl/wifidriver/rtl8188gu/os_dep/linux/ioctl_mp.c:1224:2: warning: ISO C90 forbids variable length array ‘input’ [-Wvla]
  char input[wrqu->length];
  ^
/home/yl/wifidriver/rtl8188gu/os_dep/linux/ioctl_mp.c: In function ‘rtw_mp_SetRFPath’:
/home/yl/wifidriver/rtl8188gu/os_dep/linux/ioctl_mp.c:1250:2: warning: ISO C90 forbids variable length array ‘input’ [-Wvla]
  char input[wrqu->length];
  ^
/home/yl/wifidriver/rtl8188gu/os_dep/linux/ioctl_mp.c: In function ‘rtw_mp_QueryDrv’:
/home/yl/wifidriver/rtl8188gu/os_dep/linux/ioctl_mp.c:1298:2: warning: ISO C90 forbids variable length array ‘input’ [-Wvla]
  char input[wrqu->data.length];
  ^
/home/yl/wifidriver/rtl8188gu/os_dep/linux/ioctl_mp.c: In function ‘rtw_mp_PwrCtlDM’:
/home/yl/wifidriver/rtl8188gu/os_dep/linux/ioctl_mp.c:1327:2: warning: ISO C90 forbids variable length array ‘input’ [-Wvla]
  u8  input[wrqu->length];
  ^
  CC [M]  /home/yl/wifidriver/rtl8188gu/hal/hal_intf.o
  CC [M]  /home/yl/wifidriver/rtl8188gu/hal/hal_com.o
  CC [M]  /home/yl/wifidriver/rtl8188gu/hal/hal_com_phycfg.o
  CC [M]  /home/yl/wifidriver/rtl8188gu/hal/hal_phy.o
  CC [M]  /home/yl/wifidriver/rtl8188gu/hal/hal_dm.o
  CC [M]  /home/yl/wifidriver/rtl8188gu/hal/hal_dm_acs.o
  CC [M]  /home/yl/wifidriver/rtl8188gu/hal/hal_btcoex_wifionly.o
  CC [M]  /home/yl/wifidriver/rtl8188gu/hal/hal_btcoex.o
  CC [M]  /home/yl/wifidriver/rtl8188gu/hal/hal_mp.o
  CC [M]  /home/yl/wifidriver/rtl8188gu/hal/hal_mcc.o
  CC [M]  /home/yl/wifidriver/rtl8188gu/hal/hal_hci/hal_usb.o
  CC [M]  /home/yl/wifidriver/rtl8188gu/hal/led/hal_usb_led.o
  CC [M]  /home/yl/wifidriver/rtl8188gu/hal/HalPwrSeqCmd.o
  CC [M]  /home/yl/wifidriver/rtl8188gu/hal/rtl8710b/Hal8710BPwrSeq.o
  CC [M]  /home/yl/wifidriver/rtl8188gu/hal/rtl8710b/rtl8710b_sreset.o
  CC [M]  /home/yl/wifidriver/rtl8188gu/hal/rtl8710b/rtl8710b_hal_init.o
  CC [M]  /home/yl/wifidriver/rtl8188gu/hal/rtl8710b/rtl8710b_phycfg.o
  CC [M]  /home/yl/wifidriver/rtl8188gu/hal/rtl8710b/rtl8710b_rf6052.o
  CC [M]  /home/yl/wifidriver/rtl8188gu/hal/rtl8710b/rtl8710b_dm.o
  CC [M]  /home/yl/wifidriver/rtl8188gu/hal/rtl8710b/rtl8710b_rxdesc.o
  CC [M]  /home/yl/wifidriver/rtl8188gu/hal/rtl8710b/rtl8710b_cmd.o
  CC [M]  /home/yl/wifidriver/rtl8188gu/hal/rtl8710b/hal8710b_fw.o
  CC [M]  /home/yl/wifidriver/rtl8188gu/hal/rtl8710b/rtl8710b_lps_poff.o
  CC [M]  /home/yl/wifidriver/rtl8188gu/hal/rtl8710b/usb/usb_halinit.o
  CC [M]  /home/yl/wifidriver/rtl8188gu/hal/rtl8710b/usb/rtl8710bu_led.o
  CC [M]  /home/yl/wifidriver/rtl8188gu/hal/rtl8710b/usb/rtl8710bu_xmit.o
  CC [M]  /home/yl/wifidriver/rtl8188gu/hal/rtl8710b/usb/rtl8710bu_recv.o
  CC [M]  /home/yl/wifidriver/rtl8188gu/hal/rtl8710b/usb/usb_ops.o
  CC [M]  /home/yl/wifidriver/rtl8188gu/hal/efuse/rtl8710b/HalEfuseMask8710B_USB.o
  CC [M]  /home/yl/wifidriver/rtl8188gu/hal/phydm/phydm_debug.o
  CC [M]  /home/yl/wifidriver/rtl8188gu/hal/phydm/phydm_antdiv.o
  CC [M]  /home/yl/wifidriver/rtl8188gu/hal/phydm/phydm_soml.o
  CC [M]  /home/yl/wifidriver/rtl8188gu/hal/phydm/phydm_smt_ant.o
  CC [M]  /home/yl/wifidriver/rtl8188gu/hal/phydm/phydm_antdect.o
  CC [M]  /home/yl/wifidriver/rtl8188gu/hal/phydm/phydm_interface.o
  CC [M]  /home/yl/wifidriver/rtl8188gu/hal/phydm/phydm_phystatus.o
  CC [M]  /home/yl/wifidriver/rtl8188gu/hal/phydm/phydm_hwconfig.o
  CC [M]  /home/yl/wifidriver/rtl8188gu/hal/phydm/phydm.o
  CC [M]  /home/yl/wifidriver/rtl8188gu/hal/phydm/phydm_dig.o
  CC [M]  /home/yl/wifidriver/rtl8188gu/hal/phydm/phydm_pathdiv.o
  CC [M]  /home/yl/wifidriver/rtl8188gu/hal/phydm/phydm_rainfo.o
  CC [M]  /home/yl/wifidriver/rtl8188gu/hal/phydm/phydm_dynamictxpower.o
  CC [M]  /home/yl/wifidriver/rtl8188gu/hal/phydm/phydm_adaptivity.o
  CC [M]  /home/yl/wifidriver/rtl8188gu/hal/phydm/phydm_cfotracking.o
  CC [M]  /home/yl/wifidriver/rtl8188gu/hal/phydm/phydm_noisemonitor.o
  CC [M]  /home/yl/wifidriver/rtl8188gu/hal/phydm/phydm_acs.o
  CC [M]  /home/yl/wifidriver/rtl8188gu/hal/phydm/phydm_beamforming.o
  CC [M]  /home/yl/wifidriver/rtl8188gu/hal/phydm/phydm_dfs.o
  CC [M]  /home/yl/wifidriver/rtl8188gu/hal/phydm/txbf/halcomtxbf.o
  CC [M]  /home/yl/wifidriver/rtl8188gu/hal/phydm/txbf/haltxbfinterface.o
  CC [M]  /home/yl/wifidriver/rtl8188gu/hal/phydm/txbf/phydm_hal_txbf_api.o
  CC [M]  /home/yl/wifidriver/rtl8188gu/hal/phydm/phydm_adc_sampling.o
  CC [M]  /home/yl/wifidriver/rtl8188gu/hal/phydm/phydm_ccx.o
  CC [M]  /home/yl/wifidriver/rtl8188gu/hal/phydm/phydm_psd.o
  CC [M]  /home/yl/wifidriver/rtl8188gu/hal/phydm/phydm_primary_cca.o
  CC [M]  /home/yl/wifidriver/rtl8188gu/hal/phydm/phydm_cck_pd.o
  CC [M]  /home/yl/wifidriver/rtl8188gu/hal/phydm/phydm_rssi_monitor.o
  CC [M]  /home/yl/wifidriver/rtl8188gu/hal/phydm/phydm_auto_dbg.o
  CC [M]  /home/yl/wifidriver/rtl8188gu/hal/phydm/phydm_math_lib.o
  CC [M]  /home/yl/wifidriver/rtl8188gu/hal/phydm/phydm_api.o
  CC [M]  /home/yl/wifidriver/rtl8188gu/hal/phydm/phydm_pow_train.o
  CC [M]  /home/yl/wifidriver/rtl8188gu/hal/phydm/halrf/halrf.o
  CC [M]  /home/yl/wifidriver/rtl8188gu/hal/phydm/halrf/halphyrf_ce.o
  CC [M]  /home/yl/wifidriver/rtl8188gu/hal/phydm/halrf/halrf_powertracking_ce.o
  CC [M]  /home/yl/wifidriver/rtl8188gu/hal/phydm/halrf/halrf_powertracking.o
  CC [M]  /home/yl/wifidriver/rtl8188gu/hal/phydm/halrf/halrf_kfree.o
  CC [M]  /home/yl/wifidriver/rtl8188gu/hal/phydm/rtl8710b/halhwimg8710b_bb.o
  CC [M]  /home/yl/wifidriver/rtl8188gu/hal/phydm/rtl8710b/halhwimg8710b_mac.o
  CC [M]  /home/yl/wifidriver/rtl8188gu/hal/phydm/rtl8710b/halhwimg8710b_rf.o
  CC [M]  /home/yl/wifidriver/rtl8188gu/hal/phydm/rtl8710b/phydm_regconfig8710b.o
  CC [M]  /home/yl/wifidriver/rtl8188gu/hal/phydm/rtl8710b/phydm_rtl8710b.o
  CC [M]  /home/yl/wifidriver/rtl8188gu/hal/phydm/halrf/rtl8710b/halrf_8710b.o
  CC [M]  /home/yl/wifidriver/rtl8188gu/hal/btc/halbtc8723bwifionly.o
  CC [M]  /home/yl/wifidriver/rtl8188gu/hal/btc/halbtc8822bwifionly.o
  CC [M]  /home/yl/wifidriver/rtl8188gu/hal/btc/halbtc8821cwifionly.o
  CC [M]  /home/yl/wifidriver/rtl8188gu/platform/platform_ops.o
  CC [M]  /home/yl/wifidriver/rtl8188gu/core/rtw_mp.o
  LD [M]  /home/yl/wifidriver/rtl8188gu/8188gu.o
  Building modules, stage 2.
  MODPOST 1 modules
  CC      /home/yl/wifidriver/rtl8188gu/8188gu.mod.o
  LD [M]  /home/yl/wifidriver/rtl8188gu/8188gu.ko
make[1]: Leaving directory '/usr/src/linux-headers-5.3.0-28-generic'

-----------------------------------------------------------------------------------------------------------------
END OF COMPILE OUTPUT  

when i first insert the adapter to my pc , its recognized as a usb storage device , the storage contain the windows driver,
lsusb:

**Bus 001 Device 015: ID 0bda:1a2b Realtek Semiconductor Corp.** 

then i chaned the usb mode 
**sudo usb_modeswitch -KW -v 0bda -p 1a2b**         

 now it becomes

****Bus 001 Device 016: ID 0bda:b711 Realtek Semiconductor Corp.**** 

I searched thr '0bda:b711' device , its an rtl8188gu , 

dmesgh output of **0bda:b711** is:

[ 4544.512321] usb 1-1: new high-speed USB device number 16 using xhci_hcd
[ 4544.660806] usb 1-1: New USB device found, idVendor=0bda, idProduct=b711, bcdDevice= 2.00
[ 4544.660811] usb 1-1: New USB device strings: Mfr=1, Product=2, SerialNumber=3
[ 4544.660814] usb 1-1: Product: 802.11n WLAN Adapter
[ 4544.660817] usb 1-1: Manufacturer: Realtek
[ 4544.660820] usb 1-1: SerialNumber: 00E04CB82101
[ 4547.236353] Chip Version Info: CHIP_8188E_Normal_Chip_TSMC_A_CUT_1T1R_RomVer(0)
[ 4547.236356] EEPROM ID(0xffff) is invalid!!
[ 4547.236357] EEPROM ID = 0xffff
[ 4547.254789] r8188eu 1-1:1.0 wlx00e04c818802: renamed from wlan0

**Comment by lwfinger** [comment]
If you had bothered to read any of the closed issues in this repo, you would have discovered that there are exactly ZERO Linux drivers for this chip. We did find a Windows XP driver that might have been used with NDISWrapper, but it requires two Windows routines not currently in the wrapper. One of them was trivial; however, the other must be emulated, and Windows has no description that would allow that to be done, at least not by me.

**Comment by yanlei2017** [comment]
you are so kind and patient enough, thank you so much ,i suggest you to write the notice in readme.md 😇

**Comment by lwfinger** [comment]
Why? My experience is that no one reads README.md anyway.
